// Central icon registry for UI chrome and timeline types. Components reference
// icons by name (<Icon name="Settings01Icon" />) without their own hugeicons
// import. Named imports stay tree-shakeable — only icons listed here are
// pulled onto pages that use <Icon>.
//
// Weather condition icons stay in WeatherStatus (top bar) and WeatherWidget
// (Now page) as local API-driven maps — not in this registry. StatusBar already
// loads them site-wide; keeping them out of icons.js avoids also tying them to
// every <Icon> consumer. Add a new UI icon by adding its export name to both
// lists below.
import {
    Airplane01Icon,
    AirplaneTakeOff01Icon,
    Alert02Icon,
    ArrowDown01Icon,
    ArrowLeft01Icon,
    ArrowRight01Icon,
    ArrowUp01Icon,
    ArrowUpRight01Icon,
    BookOpen01Icon,
    Calendar03Icon,
    CalendarFavorite01Icon,
    Cancel01Icon,
    CancelCircleIcon,
    Car03Icon,
    CenterFocusIcon,
    ChartColumnIcon,
    CheckmarkCircle02Icon,
    Clock01Icon,
    CommandIcon,
    Copy01Icon,
    Delete02Icon,
    DragDropVerticalIcon,
    File01Icon,
    Film01Icon,
    FireIcon,
    GithubIcon,
    GridViewIcon,
    Home01Icon,
    Image01Icon,
    InformationCircleIcon,
    Link04Icon,
    Location01Icon,
    MapsLocation01Icon,
    Menu01Icon,
    Mic01Icon,
    Moon02Icon,
    NewTwitterIcon,
    Note01Icon,
    PaintBoardIcon,
    PauseIcon,
    PetrolPumpIcon,
    PlayIcon,
    PlusSignIcon,
    PodcastIcon,
    RefreshIcon,
    Restaurant01Icon,
    RocketIcon,
    RssIcon,
    Search01Icon,
    Settings01Icon,
    SourceCodeIcon,
    SparklesIcon,
    StarIcon,
    Tag01Icon,
    Tick02Icon,
    Ticket01Icon,
    UserIcon,
    WorkoutRunIcon,
    ZoomInAreaIcon,
} from '@hugeicons-pro/core-stroke-rounded';

// Name -> icon lookup used by Icon.vue's `name` prop.
export const icons = {
    Airplane01Icon,
    AirplaneTakeOff01Icon,
    Alert02Icon,
    ArrowDown01Icon,
    ArrowLeft01Icon,
    ArrowRight01Icon,
    ArrowUp01Icon,
    ArrowUpRight01Icon,
    BookOpen01Icon,
    Calendar03Icon,
    CalendarFavorite01Icon,
    Cancel01Icon,
    CancelCircleIcon,
    Car03Icon,
    CenterFocusIcon,
    ChartColumnIcon,
    CheckmarkCircle02Icon,
    Clock01Icon,
    CommandIcon,
    Copy01Icon,
    Delete02Icon,
    DragDropVerticalIcon,
    File01Icon,
    Film01Icon,
    FireIcon,
    GithubIcon,
    GridViewIcon,
    Home01Icon,
    Image01Icon,
    InformationCircleIcon,
    Link04Icon,
    Location01Icon,
    MapsLocation01Icon,
    Menu01Icon,
    Mic01Icon,
    Moon02Icon,
    NewTwitterIcon,
    Note01Icon,
    PaintBoardIcon,
    PauseIcon,
    PetrolPumpIcon,
    PlayIcon,
    PlusSignIcon,
    PodcastIcon,
    RefreshIcon,
    Restaurant01Icon,
    RocketIcon,
    RssIcon,
    Search01Icon,
    Settings01Icon,
    SourceCodeIcon,
    SparklesIcon,
    StarIcon,
    Tag01Icon,
    Tick02Icon,
    Ticket01Icon,
    UserIcon,
    WorkoutRunIcon,
    ZoomInAreaIcon,
};
