import { keyOf } from './words.js';

const EMOJI = {
    run: '🏃',
    ran: '🏃',
    running: '🏃',
    walk: '🚶',
    walked: '🚶',
    walking: '🚶',
    ride: '🚴',
    cycled: '🚴',
    cycling: '🚴',
    bike: '🚲',
    swim: '🏊',
    swimming: '🏊',
    gym: '🏋️',
    workout: '💪',
    flight: '✈️',
    flew: '✈️',
    plane: '✈️',
    airport: '🛫',
    car: '🚗',
    fuel: '⛽',
    petrol: '⛽',
    train: '🚆',
    bus: '🚌',
    coffee: '☕',
    tea: '🍵',
    beer: '🍺',
    wine: '🍷',
    food: '🍔',
    pizza: '🍕',
    breakfast: '🥞',
    lunch: '🥪',
    dinner: '🍽️',
    cake: '🍰',
    sleep: '😴',
    slept: '😴',
    book: '📚',
    read: '📖',
    film: '🎬',
    movie: '🎬',
    episode: '🎞️',
    tv: '📺',
    music: '🎵',
    podcast: '🎧',
    game: '🎮',
    photo: '📷',
    note: '📝',
    article: '📰',
    story: '📖',
    map: '🗺️',
    place: '📍',
    event: '🎟️',
    home: '🏠',
    work: '💼',
    time: '⏰',
    today: '📅',
    week: '🗓️',
    year: '📆',
    stats: '📊',
    search: '🔍',
    settings: '⚙️',
    more: '➕',
    now: '👉',
    love: '❤️',
    heart: '❤️',
    happy: '😊',
    sad: '😢',
    fun: '🎉',
    party: '🎉',
    sun: '☀️',
    rain: '🌧️',
    snow: '❄️',
    weather: '🌦️',
    hot: '🔥',
    cold: '🥶',
    dog: '🐶',
    cat: '🐱',
    world: '🌍',
    star: '⭐',
    money: '💷',
    phone: '📱',
    computer: '💻',
    code: '💻',
    idea: '💡',
    birthday: '🎂',
    christmas: '🎄',
    yes: '👍',
    no: '👎',
    ok: '👌',
};

/**
 * Swap a word for its emoji when we know one, trying the singular too.
 * @param {string} word
 * @returns {string}
 */
export function toEmoji(word) {
    const key = keyOf(word);

    return EMOJI[key] ?? (key.endsWith('s') ? EMOJI[key.slice(0, -1)] : null) ?? word;
}
