import { keyOf, matchCase } from './words.js';

const PIRATE = {
    hello: 'ahoy',
    hi: 'ahoy',
    hey: 'ahoy',
    yes: 'aye',
    yeah: 'aye',
    ok: 'aye',
    okay: 'aye',
    no: 'nay',
    thanks: 'thank ye',
    sorry: 'arrr',
    please: 'if ye please',
    my: 'me',
    you: 'ye',
    your: 'yer',
    "you're": 'ye be',
    "you'll": "ye'll",
    "it's": "'tis",
    is: 'be',
    are: 'be',
    the: "th'",
    of: "o'",
    and: "an'",
    to: "t'",
    for: 'fer',
    with: "wi'",
    have: "'ave",
    had: "'ad",
    having: "'avin'",
    about: "'bout",
    what: 'wot',
    where: 'whar',
    here: "'ere",
    there: 'thar',
    over: "o'er",
    never: "ne'er",
    ever: "e'er",
    before: 'afore',
    them: "'em",
    today: 'this day',
    friend: 'matey',
    friends: 'hearties',
    mate: 'matey',
    people: 'landlubbers',
    everyone: 'all hands',
    boy: 'lad',
    girl: 'lass',
    dad: "ol' man",
    boss: "cap'n",
    developer: 'shipwright',
    colleague: 'shipmate',
    ate: 'scoffed',
    eat: 'scoff',
    slept: 'kipped',
    sleep: 'kip',
    woke: 'came about',
    went: 'sailed',
    go: 'sail',
    drove: 'sailed',
    drive: 'sail',
    walked: 'swaggered',
    walk: 'swagger',
    ran: 'scurried',
    run: 'scurry',
    worked: 'toiled',
    work: 'toil',
    watched: 'spied',
    watch: 'spy',
    lifted: 'hoisted',
    burned: 'plundered',
    tracked: 'charted',
    track: 'chart',
    look: 'behold',
    think: 'reckon',
    stop: 'avast',
    food: 'grub',
    drink: 'swig',
    drinks: 'swigs',
    coffee: 'grog',
    beer: 'grog',
    water: 'bilge water',
    home: 'port',
    station: 'harbour',
    restaurant: 'tavern',
    pub: 'tavern',
    cafe: 'galley',
    kitchen: 'galley',
    hotel: 'inn',
    shop: 'tradin\' post',
    bed: 'hammock',
    internet: 'seven seas',
    money: 'doubloons',
    cash: 'doubloons',
    stuff: 'booty',
    car: 'ship',
    plane: 'sky ship',
    weight: 'ballast',
    podcast: 'sea shanty',
    hours: 'bells',
    trip: 'voyage',
    trips: 'voyages',
    flight: 'voyage',
    flights: 'voyages',
    travel: 'sail',
    map: 'treasure map',
    maps: 'treasure maps',
    wow: 'blimey',
    good: 'fine',
    nice: 'fine',
    awesome: 'shipshape',
    great: 'mighty',
    big: 'mighty',
    very: 'mighty',
    much: 'mighty much',
    small: 'wee',
    little: 'wee',
    old: 'barnacled',
    weird: 'rum',
    stats: 'plunder',
    story: 'yarn',
    stories: 'yarns',
    articles: 'tales',
    notes: 'scribblins',
    timeline: "captain's log",
    search: 'seek',
    photos: 'portraits',
    settings: "riggin'",
};

/**
 * Say a word like a pirate: known words are swapped, and running becomes runnin'.
 * @param {string} word
 * @returns {string}
 */
export function toPirate(word) {
    const key = keyOf(word);

    if (PIRATE[key]) {
        return matchCase(word, PIRATE[key]);
    }

    return key.length > 4 && key.endsWith('ing') ? `${word.slice(0, -1)}'` : word;
}
