<?php

namespace App\Support;

use App\Data\TypeMeta;
use App\Datasets\Dataset;
use App\Datasets\Datasets;
use App\Enums\TimelineType;

/**
 * How every data type is drawn and named: icon, labels, archive href, accent
 * token and palette keywords, for the non-dataset link and authoring types,
 * plus a view over App\Datasets for the timeline types.
 *
 * This is the structural half of the pair; TypeColors is the colour half, and
 * reads the hues themselves out of the stylesheet. Between them nothing about a
 * type is written down twice.
 *
 * The frontend gets this table as resources/js/types.generated.js, written by
 * `php artisan types:sync` and kept honest by tests/Feature/TypeCatalogueTest.php.
 */
final class TypeCatalogue
{
    /** Where the generated frontend module is written. */
    public const MODULE = 'resources/js/types.generated.js';

    /** @var array<string, TypeMeta>|null */
    private static ?array $all = null;

    /**
     * The timeline data types, in dataset order.
     *
     * @return list<TypeMeta>
     */
    public static function timeline(): array
    {
        return array_values(array_map(fn (Dataset $dataset): TypeMeta => new TypeMeta(
            key: $dataset->type()->value,
            icon: $dataset->icon(),
            label: $dataset->label(),
            accent: $dataset->type()->accent(),
            plural: $dataset->plural(),
            href: '/'.$dataset->slug(),
            keywords: $dataset->keywords(),
            eyebrow: $dataset->eyebrow(),
            noun: $dataset->countNouns()[0],
            nounPlural: $dataset->countNouns()[1],
            kind: $dataset->kind()->value,
        ), Datasets::all()));
    }

    /**
     * The other things an internal link can point at, so a link preview has a
     * glyph for each. See App\Links\Resolvers. Their `href` is where a link of
     * that kind goes, not an archive, so they carry no plural and stay out of
     * the palette's Archives list.
     *
     * @return list<TypeMeta>
     */
    public static function links(): array
    {
        return [
            new TypeMeta(key: 'story', icon: 'BookOpen01Icon', label: 'Story', accent: 'article', href: '/stories'),
            new TypeMeta(key: 'page', icon: 'File02Icon', label: 'Page', accent: 'article', plural: 'Pages'),
            new TypeMeta(key: 'period', icon: 'Calendar03Icon', label: 'Archive', accent: 'article', href: '/'),
            new TypeMeta(key: 'tag', icon: 'Tag01Icon', label: 'Tag', accent: 'article', href: '/tags'),
            new TypeMeta(key: 'live', icon: 'Clock01Icon', label: 'Now', accent: 'activity', href: '/now'),
        ];
    }

    /**
     * Types that exist only as something to write. A book is a Media row
     * narrowed to MediaType::Book, so it takes the media hue.
     *
     * @return list<TypeMeta>
     */
    public static function authoring(): array
    {
        return [
            new TypeMeta(key: 'book', icon: 'BookOpen01Icon', label: 'Book', accent: 'media'),
        ];
    }

    /**
     * Every type a card, link preview, icon lookup or /new form can be handed.
     *
     * @return array<string, TypeMeta>
     */
    public static function all(): array
    {
        if (self::$all !== null) {
            return self::$all;
        }

        $all = [];

        foreach ([...self::timeline(), ...self::links(), ...self::authoring()] as $meta) {
            $all[$meta->key] = $meta;
        }

        return self::$all = $all;
    }

    public static function for(string $key): ?TypeMeta
    {
        return self::all()[$key] ?? null;
    }

    /**
     * The row for a timeline type, which the catalogue is guaranteed to hold:
     * every case is declared in timeline() above, and a test asserts it.
     */
    public static function forType(TimelineType $type): TypeMeta
    {
        return self::all()[$type->value];
    }

    /**
     * The contents of the generated frontend module. Returned as a string rather
     * than an array so the sync test can compare the committed bytes: comparing
     * decoded values would pass while the file on disk differed.
     */
    public static function module(): string
    {
        $groups = [
            'timelineTypes' => self::timeline(),
            'linkTypes' => self::links(),
            'authoringTypes' => self::authoring(),
        ];

        $blocks = [];

        foreach ($groups as $name => $types) {
            $rows = array_map(
                fn (TypeMeta $meta): string => sprintf('    %s: %s,', self::property($meta->key), self::literal($meta->toArray())),
                $types,
            );

            $blocks[] = sprintf("export const %s = {\n%s\n};", $name, implode("\n", $rows));
        }

        return implode("\n\n", [self::header(), ...$blocks])."\n";
    }

    private static function header(): string
    {
        return <<<'JS'
            // Generated by `php artisan types:sync`. Do not edit.
            //
            // The single source of truth is App\Datasets (timeline types) and
            // App\Support\TypeCatalogue (link and authoring types). Colours are not
            // here: `accent` is a --color-* token key, defined in resources/css/theme.css
            // and resources/css/dark.css so a type's hue follows the reader's scheme.
            JS;
    }

    /**
     * A key as a JS object property, quoted only when it is not a bare identifier.
     * Every key today is one, so this changes nothing until a hyphenated type key
     * appears and would otherwise emit a module that will not parse.
     */
    private static function property(string $key): string
    {
        return preg_match('/^[A-Za-z_$][A-Za-z0-9_$]*$/', $key) === 1 ? $key : "'".$key."'";
    }

    /**
     * A JS object literal, single-quoted to match the hand-written modules.
     *
     * @param  array<string, string>  $values
     */
    private static function literal(array $values): string
    {
        $pairs = [];

        foreach ($values as $key => $value) {
            $pairs[] = sprintf("%s: '%s'", $key, str_replace(['\\', "'"], ['\\\\', "\\'"], $value));
        }

        return '{ '.implode(', ', $pairs).' }';
    }
}
